# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi.json:
  info-license:
    - '#/info'
  no-unused-components:
    - '#/components/schemas/account_types__types__all'
    - '#/components/schemas/funds_transfer_types__manual'
    - '#/components/schemas/asset_transfer_method__asset_transfer_types'
    - '#/components/schemas/asset_transfer_method__transfer_directions'
    - '#/components/schemas/resource_tokens__resource_token_types'
    - '#/components/schemas/account_policies__account_risk_level'
    - >-
      #/components/schemas/account_policies__allowed_incoming_funds_transfer_types
    - >-
      #/components/schemas/account_policies__allowed_outgoing_funds_transfer_types
    - '#/components/schemas/account_policies__default_currency'
    - '#/components/schemas/account_policies__required_kyc_documents'
    - '#/components/schemas/types__ipv4_address'
    - '#/components/schemas/currency__default'
    - '#/components/schemas/account_statements__statement'
    - '#/components/schemas/account_statements__batches'
    - '#/components/schemas/addresses__update'
    - '#/components/schemas/funds_transfer_methods__transfer_type'
    - '#/components/schemas/reconcile_items__update'
    - '#/components/schemas/bank_reports__create'
    - '#/components/schemas/kyc_document_checks__reprocess'
    - '#/components/schemas/contacts__create'
    - '#/components/schemas/accounts__set_rule_group'
    - '#/components/schemas/accounts__reverse_pending_closure'
    - >-
      #/components/schemas/contact_funds_transfer_references__settle_funds_transfer
    - '#/components/schemas/account_cash_transfers__reverse'
    - '#/components/schemas/bank_transactions__create'
    - '#/components/schemas/countries__update'
    - '#/components/schemas/nacha_batches__create'
    - '#/components/schemas/nacha_batches__settle'
    - '#/components/schemas/21000__error'
    - '#/components/schemas/21100__error'
    - '#/components/schemas/funds_transfer_limit_exemptions__create'
    - '#/components/schemas/funds_transfer_limit_exemptions__update'
    - '#/components/schemas/67005__error'
    - '#/components/schemas/67000__error'
    - '#/components/schemas/67001__error'
    - '#/components/schemas/67002__error'
    - '#/components/schemas/67003__error'
    - '#/components/schemas/67004__error'
    - '#/components/schemas/card_images__create'
    - '#/components/schemas/asset_transfers__settle'
    - '#/components/schemas/64000__error'
    - '#/components/schemas/incoming_wire_batch_rows__update'
    - '#/components/schemas/rules__update'
    - '#/components/schemas/rules__rule_base'
    - '#/components/schemas/admin_notes__update'
    - '#/components/schemas/access_policies__destroy'
    - '#/components/schemas/user_policies__create'
    - '#/components/schemas/account_reviews__create'
    - '#/components/schemas/admin_funds_transfers__create'
    - '#/components/schemas/trade_desk_routings__update'
    - '#/components/schemas/trade_desk_routings__create'
    - '#/components/schemas/nacha_configs__create'
    - '#/components/schemas/nacha_configs__update'
    - '#/components/schemas/authorization_rule_groups__update'
    - '#/components/schemas/31000__error'
    - '#/components/schemas/apto_corporations__create'
    - '#/components/schemas/apto_corporations__update'
    - '#/components/schemas/account_risk_reviews__create'
    - '#/components/schemas/card_holder_verifications__sandbox__update'
    - '#/components/schemas/suspense_wires__approve'
    - '#/components/schemas/suspense_wires__reject'
    - '#/components/schemas/suspense_wires__settle'
    - '#/components/schemas/4003__error'
    - '#/components/schemas/4002__error'
    - '#/components/schemas/4001__error'
    - '#/components/schemas/4005__error'
    - '#/components/schemas/4000__error'
    - '#/components/schemas/4004__error'
    - '#/components/schemas/outgoing_wire_batches__create'
    - '#/components/schemas/outgoing_wire_batches__settle'
    - '#/components/schemas/85001__error'
    - '#/components/schemas/signet_transactions__send'
    - '#/components/schemas/agreement_templates__update'
    - '#/components/schemas/aml_checks__create'
    - '#/components/schemas/trade_desks__update'
    - '#/components/schemas/incoming_wire_batches__update_rows'
    - '#/components/schemas/22000__error'
    - '#/components/schemas/card_designs__create'
    - '#/components/schemas/card_designs__update'
    - '#/components/schemas/asset_trade_desks__update'
    - '#/components/schemas/asset_trade_desks__create'
    - '#/components/schemas/cip_checks__create'
    - '#/components/schemas/cip_checks__update'
    - '#/components/schemas/funds_transfer_methods__deep__test__create'
    - '#/components/schemas/contributions__create_test'
    - '#/components/schemas/account_reviews__response_wrapper_array'
    - '#/components/schemas/account_reviews__filter'
    - '#/components/schemas/account_reviews__sort'
    - '#/components/schemas/account_reviews__include'
    - '#/components/schemas/account_risk_reviews__response_wrapper_array'
    - '#/components/schemas/account_risk_reviews__filter'
    - '#/components/schemas/account_risk_reviews__sort'
    - '#/components/schemas/account_risk_reviews__include'
    - '#/components/schemas/account_statement_batches__filter'
    - '#/components/schemas/account_statement_batches__sort'
    - '#/components/schemas/account_statement_batches__include'
    - '#/components/schemas/account_statement_batches__response_wrapper_array'
    - '#/components/schemas/activities__response_wrapper_array'
    - '#/components/schemas/activities__filter'
    - '#/components/schemas/activities__sort'
    - '#/components/schemas/activities__include'
    - '#/components/schemas/admin_funds_transfers__included'
    - '#/components/schemas/admin_funds_transfers__response'
    - '#/components/schemas/admin_funds_transfers__filter'
    - '#/components/schemas/admin_funds_transfers__sort'
    - '#/components/schemas/admin_funds_transfers__include'
    - '#/components/schemas/admin_notes__response_wrapper_array'
    - '#/components/schemas/admin_notes__filter'
    - '#/components/schemas/admin_notes__sort'
    - '#/components/schemas/admin_notes__include'
    - '#/components/schemas/agreement_previews__filter'
    - '#/components/schemas/agreement_previews__sort'
    - '#/components/schemas/agreement_templates__response_wrapper_array'
    - '#/components/schemas/agreement_templates__filter'
    - '#/components/schemas/agreement_templates__sort'
    - '#/components/schemas/agreement_templates__include'
    - '#/components/schemas/api_requests__response_wrapper_array'
    - '#/components/schemas/api_requests__filter'
    - '#/components/schemas/api_requests__sort'
    - '#/components/schemas/api_requests__include'
    - '#/components/schemas/apto_corporations__response_wrapper_array'
    - '#/components/schemas/apto_corporations__filter'
    - '#/components/schemas/apto_corporations__sort'
    - '#/components/schemas/apto_corporations__include'
    - '#/components/schemas/apto_settlements__response_wrapper_array'
    - '#/components/schemas/apto_settlements__filter'
    - '#/components/schemas/apto_settlements__sort'
    - '#/components/schemas/apto_settlements__include'
    - '#/components/schemas/asset_trade_desks__response_wrapper_array'
    - '#/components/schemas/asset_trade_desks__filter'
    - '#/components/schemas/asset_trade_desks__sort'
    - '#/components/schemas/asset_trade_desks__include'
    - '#/components/schemas/bank_accounts__response_wrapper_array'
    - '#/components/schemas/bank_accounts__filter'
    - '#/components/schemas/bank_accounts__sort'
    - '#/components/schemas/bank_accounts__include'
    - '#/components/schemas/bank_reports__response_wrapper_array'
    - '#/components/schemas/bank_reports__filter'
    - '#/components/schemas/bank_reports__sort'
    - '#/components/schemas/bank_reports__include'
    - '#/components/schemas/bank_transactions__response_wrapper_array'
    - '#/components/schemas/bank_transactions__filter'
    - '#/components/schemas/bank_transactions__sort'
    - '#/components/schemas/bank_transactions__include'
    - '#/components/schemas/card_designs__response_wrapper_array'
    - '#/components/schemas/card_designs__filter'
    - '#/components/schemas/card_designs__sort'
    - '#/components/schemas/card_designs__include'
    - '#/components/schemas/card_holder_verifications__filter'
    - '#/components/schemas/card_holder_verifications__sort'
    - '#/components/schemas/card_images__response_wrapper_array'
    - '#/components/schemas/card_images__filter'
    - '#/components/schemas/card_images__sort'
    - '#/components/schemas/card_images__include'
    - '#/components/schemas/chargeback_batches__response_wrapper_array'
    - '#/components/schemas/chargeback_batches__filter'
    - '#/components/schemas/chargeback_batches__sort'
    - '#/components/schemas/chargeback_batches__include'
    - '#/components/schemas/contact_histories__response_wrapper_array'
    - '#/components/schemas/contact_histories__filter'
    - '#/components/schemas/contact_histories__sort'
    - '#/components/schemas/contact_histories__include'
    - '#/components/schemas/disbursement_owner_verifications__included'
    - '#/components/schemas/disbursement_owner_verifications__filter'
    - '#/components/schemas/disbursement_owner_verifications__sort'
    - '#/components/schemas/error_codes__response_wrapper_array'
    - '#/components/schemas/error_codes__filter'
    - '#/components/schemas/error_codes__sort'
    - '#/components/schemas/error_codes__include'
    - >-
      #/components/schemas/funds_transfer_limit_exemptions__response_wrapper_array
    - '#/components/schemas/funds_transfer_limit_exemptions__filter'
    - '#/components/schemas/funds_transfer_limit_exemptions__sort'
    - '#/components/schemas/funds_transfer_limit_exemptions__include'
    - '#/components/schemas/incoming_wire_batch_rows__response_wrapper_array'
    - '#/components/schemas/incoming_wire_batch_rows__filter'
    - '#/components/schemas/incoming_wire_batch_rows__sort'
    - '#/components/schemas/incoming_wire_batch_rows__include'
    - '#/components/schemas/incoming_wire_batches__filter'
    - '#/components/schemas/incoming_wire_batches__sort'
    - '#/components/schemas/incoming_wire_batches__include'
    - '#/components/schemas/incoming_wire_batches__response_wrapper_array'
    - '#/components/schemas/nacha_batches__response_wrapper_array'
    - '#/components/schemas/nacha_batches__filter'
    - '#/components/schemas/nacha_batches__sort'
    - '#/components/schemas/nacha_batches__include'
    - '#/components/schemas/nacha_configs__filter'
    - '#/components/schemas/nacha_configs__sort'
    - '#/components/schemas/nacha_configs__include'
    - '#/components/schemas/nacha_configs__response_wrapper_array'
    - '#/components/schemas/outgoing_wire_batches__response_wrapper_array'
    - '#/components/schemas/outgoing_wire_batches__filter'
    - '#/components/schemas/outgoing_wire_batches__sort'
    - '#/components/schemas/outgoing_wire_batches__include'
    - '#/components/schemas/reconcile_items__response_wrapper_array'
    - '#/components/schemas/reconcile_items__filter'
    - '#/components/schemas/reconcile_items__sort'
    - '#/components/schemas/reconcile_items__include'
    - '#/components/schemas/signet_transactions__response_wrapper_array'
    - '#/components/schemas/signet_transactions__filter'
    - '#/components/schemas/signet_transactions__sort'
    - '#/components/schemas/signet_transactions__include'
    - '#/components/schemas/suspense_wires__response_wrapper_array'
    - '#/components/schemas/suspense_wires__filter'
    - '#/components/schemas/suspense_wires__sort'
    - '#/components/schemas/suspense_wires__include'
    - '#/components/schemas/three_ds_challenges__included'
    - '#/components/schemas/three_ds_challenges__response'
    - '#/components/schemas/three_ds_challenges__filter'
    - '#/components/schemas/three_ds_challenges__sort'
    - '#/components/schemas/three_ds_challenges__include'
    - '#/components/schemas/trade_desk_failures__response_wrapper_array'
    - '#/components/schemas/trade_desk_failures__filter'
    - '#/components/schemas/trade_desk_failures__sort'
    - '#/components/schemas/trade_desk_failures__include'
    - '#/components/schemas/trade_desk_routing_groups__response_wrapper_array'
    - '#/components/schemas/trade_desk_routing_groups__filter'
    - '#/components/schemas/trade_desk_routing_groups__sort'
    - '#/components/schemas/trade_desk_routing_groups__include'
    - '#/components/schemas/trade_desk_routings__response_wrapper_array'
    - '#/components/schemas/trade_desk_routings__filter'
    - '#/components/schemas/trade_desk_routings__sort'
    - '#/components/schemas/trade_desk_routings__include'
    - '#/components/schemas/trade_desks__response_wrapper_array'
    - '#/components/schemas/trade_desks__filter'
    - '#/components/schemas/trade_desks__sort'
    - '#/components/schemas/trade_desks__include'
    - '#/components/schemas/trulioo_reports__response_wrapper_array'
    - '#/components/schemas/trulioo_reports__filter'
    - '#/components/schemas/trulioo_reports__sort'
    - '#/components/schemas/trulioo_reports__include'
    - '#/components/schemas/user_policies__filter'
    - '#/components/schemas/user_policies__sort'
    - '#/components/schemas/user_policies__include'
    - '#/components/schemas/user_policies__response_wrapper_array'
    - '#/components/schemas/user_totp_secrets__included'
    - '#/components/schemas/user_totp_secrets__filter'
    - '#/components/schemas/user_totp_secrets__sort'
    - '#/components/schemas/vantiv_requests__response_wrapper_array'
    - '#/components/schemas/vantiv_requests__filter'
    - '#/components/schemas/vantiv_requests__sort'
    - '#/components/schemas/vantiv_requests__include'
    - '#/components/schemas/wire_initiators__filter'
    - '#/components/schemas/wire_initiators__sort'
